#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     color,          sensorCOLORRED)
#pragma config(Motor,  mtr_S1_C1_1,     FR,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     BR,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     FL,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     BL,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     UL,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ULT,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     UR,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     URT,           tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S2_C1_1,    servoBall,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_2,    servoTube,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servoMvClaws,         tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servoTube2,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int a = 64;

void Servosetup()
{
	//	servo[servoClaws] = 235;
	servo[servoBall] = 127;
	servo[servoTube] = 182;
	servo[servoTube2] = 255 - ServoValue[servoTube];
	servo[servoMvClaws] = 255;
	nMotorEncoder[FR] = 0;
	nMotorEncoder[FL] = 0;
	nMotorEncoder[BR] = 0;
	nMotorEncoder[BL] = 0;
	nMotorEncoder[UR] = 0;
	nMotorEncoder[UL] = 0;
	nMotorEncoder[URT] = 0;
	nMotorEncoder[ULT] = 0;
}

void motion(int l_ramp_goal, int a)
{
	int enc;
	int pow = 100, color;
  nMotorEncoder[BR] = 0;
	nMotorEncoder[BL] = 0;
  motor[FR] = a * 100;
  motor[BR] = a * 100;
  motor[FL] = a * 100;
  motor[BL] = a * 100;
  wait1Msec(1500);
  enc = -nMotorEncoder[BR];
  nxtDisplayBigTextLine(2, "%i", enc);
  if(-a * nMotorEncoder[BR] < 10)
  {
  	while(true)
  	{
  		for (; pow >= 0; pow--)
  		{
        motor[FR] = pow;
        motor[BR] = pow;
        motor[FL] = pow;
        motor[BL] = pow;
        wait1Msec(5);
        enc = -nMotorEncoder[BR];
        nxtDisplayBigTextLine(2, "%i", enc);
      }
  	}
  }
 /* if (SensorValue[S3] == color)
  {
  	  nMotorEncoder[BR] = 0;
    	nMotorEncoder[BL] = 0;*/
	while(-a * nMotorEncoder[BR] * 0.031415 < l_ramp_goal - 50)
	{
	  motor[FR] = a * 100;
    motor[BR] = a * 100;
    motor[FL] = a * 100;
    motor[BL] = a * 100;
    enc = nMotorEncoder[BR];
    nxtDisplayBigTextLine(2, "%i", enc);
  }

  motor[FR] = -100;
  motor[BR] = -100;
  motor[FL] = -100;
  motor[BL] = -100;
//  wait1Msec(100);

  while(-a * nMotorEncoder[BR] * 0.031415 < l_ramp_goal)
	{
	  motor[FR] = a * 20;
    motor[BR] = a * 20;
    motor[FL] = a * 20;
    motor[BL] = a * 20;
  }
  servo[servoMvClaws] = 18;
  while(-a * nMotorEncoder[BR] * 0.031415 < l_ramp_goal + 20)
  {
    motor[FR] = a * 20;
    motor[BR] = a * 20;
    motor[FL] = a * 20;
    motor[BL] = a * 20;

  }

  motor[FR] = 0;
  motor[BR] = 0;
  motor[FL] = 0;
  motor[BL] = 0;
}

void elevator()
{
	int enc;
	nMotorEncoder[UL] = 0;
	motor[UR] = 100;
  motor[UL] = -100;
  motor[URT] = 100;
  motor[ULT] = -100;
  wait1Msec(1000);
  if(-nMotorEncoder[UL] < 10)
  {
    while(true)
    {
  	  motor[UR] = 0;
      motor[UL] = 0;
      motor[URT] = 0;
      motor[ULT] = 0;
    }
  }
	while(-nMotorEncoder[UL] < 12000)
	{
    motor[UR] = 100;
    motor[UL] = -100;
    motor[URT] = 100;
    motor[ULT] = -100;
    enc = -nMotorEncoder[UL];
    //nxtDisplayBigTextLine(1, "%i", enc);
  }
  motor[UR] = 0;
  motor[UL] = 0;
  motor[URT] = 0;
  motor[ULT] = 0;

 	while(nMotorEncoder[UL] < -7300)
	{
    motor[UR] = -100;
  	motor[UL] = 100;
    motor[URT] = -100;
    motor[ULT] = 100;
  }

  motor[UR] = 0;
  motor[UL] = 0;
  motor[URT] = 0;
  motor[ULT] = 0;

  servo[servoTube] = 0;
  servo[servoTube2] = 255;
  wait1Msec(3500);

  servo[servoTube] = 182;
  servo[servoTube2] = 255 - ServoValue[servoTube];

  /*while(nMotorEncoder[UL] < -10)
  {
    motor[UR] = -100;
    motor[UL] = 100;
    motor[URT] = -100;
    motor[ULT] = 100;
  }*/

  motor[UR] = 0;
  motor[UL] = 0;
  motor[URT] = 0;
  motor[ULT] = 0;
}

void rotate(float l_ramp_goal)
{
	nMotorEncoder[BR] = 0;
	while(-nMotorEncoder[BR] /*/ 1000) * 3.14159265 * 10*/ < l_ramp_goal)
	{
	  motor[FR] = 100;
    motor[BR] = 100;
    motor[FL] = -100;
    motor[BL] = -100;
  }

  motor[FR] = -100;
  motor[BR] = -100;
  motor[FL] = 100;
  motor[BL] = 100;

  motor[FR] = 0;
  motor[BR] = 0;
  motor[FL] = 0;
  motor[BL] = 0;

 // servo[servoMvClaws] = 90;
}



task main()
{
	Servosetup();
  waitForStart();
	//StartTask(stage);
	//StartTask(tube);
   servo[servoMvClaws] = 50;
   motion(320, 1);
   elevator();
   servo[servoBall] = 127;
   rotate(550);
   motion(385, -1);

	while(true)
	{
		motor[FR] = 0;
    motor[BR] = 0;
    motor[FL] = 0;
    motor[BL] = 0;
    motor[UR] = 0;
    motor[UL] = 0;
    motor[URT] = 0;
    motor[ULT] = 0;
  }
}
