#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     color,          sensorCOLORRED)
#pragma config(Motor,  mtr_S1_C1_1,     BR,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     FR,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     FL,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     BL,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     UL,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ULT,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     UR,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     URT,           tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S2_C1_1,    servoBall,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_2,    servoTube,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servoMvClaws,         tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int a = 64;

void Servosetup()
{
	//	servo[servoClaws] = 235;
	servo[servoBall] = 127;
	servo[servoTube] = 70;
	servo[servoMvClaws] = 255;
	nMotorEncoder[FR] = 0;
	nMotorEncoder[FL] = 0;
	nMotorEncoder[BR] = 0;
	nMotorEncoder[BL] = 0;
	nMotorEncoder[UR] = 0;
	nMotorEncoder[UL] = 0;
	nMotorEncoder[URT] = 0;
	nMotorEncoder[ULT] = 0;
}

void zero()
{
   motor[FR] = 0;
	 motor[FR] = 0;
	 motor[BR] = 0;
	 motor[BL] = 0;
	 motor[UR] = 0;
   motor[UL] = 0;
   motor[URT] = 0;
   motor[ULT] = 0;
}

void motion_elevator(int l, int h)
{
	nMotorEncoder[BL] = 0;
	nMotorEncoder[UL] = 0;
	while (-nMotorEncoder[BL] < l && -nMotorEncoder[UL] < h)
	{
			motor[FR] = -20;
			motor[FR] = -20;
			motor[BR] = -20;
			motor[BL] = -20;
			motor[UR] = 100;
  		motor[UL] = -100;
  		motor[URT] = 100;
  		motor[ULT] = -100;
  }
  zero();
  while (-nMotorEncoder[BL] < l)
	{
			motor[FR] = -20;
			motor[FR] = -20;
			motor[BR] = -20;
			motor[BL] = -20;
	}
	zero();
}

void motion(int l_ramp_goal, int a)
{
	int enc;
	int pow = 100;
  nMotorEncoder[FR] = 0;
	nMotorEncoder[BL] = 0;
  motor[FR] = a * 100;
  motor[BR] = a * 100;
  motor[FL] = a * 100;
  motor[BL] = a * 100;
  wait1Msec(1500);
  enc = nMotorEncoder[BL];
  nxtDisplayBigTextLine(1, "%i", enc);
  if(a * nMotorEncoder[BL] < 10)
  {
  	while(true)
  	{
  		for (; pow >= 0; pow--)
  		{
        motor[FR] = pow;
        motor[BR] = pow;
        motor[FL] = pow;
        motor[BL] = pow;
        wait1Msec(5);
        enc = nMotorEncoder[BL];
        nxtDisplayBigTextLine(2, "%i", enc);
      }
  	}
  }
 /* if (SensorValue[S3] == color)
  {
  	  nMotorEncoder[BR] = 0;
    	nMotorEncoder[BL] = 0;*/
	while(a * nMotorEncoder[BL] < l_ramp_goal - 4096)// * 1024 /(3.1415 * 10 ))// - 50)
	{
	  motor[FR] = a * 100;
    motor[BR] = a * 100;
    motor[FL] = a * 100;
    motor[BL] = a * 100;
    enc = nMotorEncoder[BL];
    nxtDisplayBigTextLine(2, "%i", enc);
  }
  for (int pow = a * 100; pow >= a * 20; pow--)
  {
  	motor[FR] = pow;
    motor[BR] = pow;
    motor[FL] = pow;
    motor[BL] = pow;
    wait1Msec(5);
  }
  while(a * nMotorEncoder[BL] < l_ramp_goal)
	{
	  motor[FR] = a * 20;
    motor[BR] = a * 20;
    motor[FL] = a * 20;
    motor[BL] = a * 20;
  }
  servo[servoMvClaws] = 18;
  while(a * nMotorEncoder[BL] < l_ramp_goal + 500)
  {
    motor[FR] = a * 20;
    motor[BR] = a * 20;
    motor[FL] = a * 20;
    motor[BL] = a * 20;

  }

  motor[FR] = 0;
  motor[BR] = 0;
  motor[FL] = 0;
  motor[BL] = 0;
}

void elevator()
{
	int enc;
	nMotorEncoder[UL] = 0;
	motor[UR] = 100;
  motor[UL] = -100;
  motor[URT] = 100;
  motor[ULT] = -100;
  wait1Msec(1000);
  if(-nMotorEncoder[UL] < 10)
  {
    while(true)
    {
  	  motor[UR] = 0;
      motor[UL] = 0;
      motor[URT] = 0;
      motor[ULT] = 0;
    }
  }

 	while(-nMotorEncoder[UL] < 7300)
	{
    motor[UR] = 100;
  	motor[UL] = -100;
    motor[URT] = 100;
    motor[ULT] = -100;
  }

  motor[UR] = 0;
  motor[UL] = 0;
  motor[URT] = 0;
  motor[ULT] = 0;

  servo[servoTube] = 245;
  wait1Msec(3500);

  servo[servoTube] = 70;

  while(nMotorEncoder[UL] < -10)
  {
    motor[UR] = -100;
    motor[UL] = 100;
    motor[URT] = -100;
    motor[ULT] = 100;
  }

  motor[UR] = 0;
  motor[UL] = 0;
  motor[URT] = 0;
  motor[ULT] = 0;
}

void R(float l_ramp_goal, int pow)
{
	nMotorEncoder[FR] = 0;
	int sign = abs(pow) / pow;
	while(sign * nMotorEncoder[FR] /*/ 1000) * 3.14159265 * 10*/ < l_ramp_goal)
	{
    motor[FR] = -pow;
    motor[BR] = -pow;
  }

  motor[FR] = pow;
  motor[BR] = pow;

  motor[FR] = 0;
  motor[BR] = 0;
  motor[FL] = 0;
  motor[BL] = 0;
}

void L(float l_ramp_goal, int pow)
{
	nMotorEncoder[BL] = 0;
	int sign = abs(pow) / pow;
	while(sign * nMotorEncoder[BL] /*/ 1000) * 3.14159265 * 10*/ < l_ramp_goal)
	{
    motor[FL] = pow;
    motor[BL] = pow;
    nxtDisplayBigTextLine(2, "%i", nMotorEncoder[FR]);
  }

  motor[FL] = pow;
  motor[BL] = pow;

  motor[FR] = 0;
  motor[BR] = 0;
  motor[FL] = 0;
  motor[BL] = 0;
}

void rotate(float l_ramp_goal)
{
	wait1Msec(500);
	nMotorEncoder[BL] = 0;
	nMotorEncoder[FR] = 0;
	while(nMotorEncoder[FR] /*/ 1000) * 3.14159265 * 10*/ < l_ramp_goal)
	{
    motor[FL] = 50;
    motor[BL] = 50;
 	  motor[FR] = -100;
    motor[BR] = -100;
  }

  motor[FL] = -100;
  motor[BL] = -100;
  motor[FR] = -100;
  motor[BR] = -100;

  motor[FR] = 0;
  motor[BR] = 0;
  motor[FL] = 0;
  motor[BL] = 0;
}



task main()
{
	 Servosetup();
   servo[servoMvClaws] = 50;
   motion(7000, 1);
   //elevator();
   rotate(1000);
   L(1000, -100);
   wait1Msec(1000);
   motion(800, 1);
   L(1000, -100);
   motion(8000,-1);
	while(true)
	{
		motor[FR] = 0;
    motor[BR] = 0;
    motor[FL] = 0;
    motor[BL] = 0;
    motor[UR] = 0;
    motor[UL] = 0;
    motor[URT] = 0;
    motor[ULT] = 0;
  }
}
