#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     color,          sensorCOLORRED)
#pragma config(Motor,  mtr_S1_C1_1,     BR,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     FR,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     FL,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     BL,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     UL,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ULT,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     UR,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     URT,           tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S2_C1_1,    servoBall,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_2,    servoTube,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servoMvClaws,         tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servoMvClaws2,        tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    servoMvClaws3,        tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int a = 64;

void L_R (int ii, int jj, int tt) // + forward; - backward
{
	motor[FR] = -jj;
	motor[FL] = -ii;
	motor[BR] = -jj;
	motor[BL] = -ii;
	wait1Msec(tt);
}

void UP (int iii, int ttt) // control of lift by "wait"
{
	motor[UR] = iii;
	motor[UL] = -iii;
	motor[URT] = iii;
	motor[ULT] = -iii;
	wait1Msec(ttt);
}

void L_R_UP (int i, int j, int k, int t)
{
	motor[FR] = -j;
	motor[FL] = -i;
	motor[BR] = -j;
	motor[BL] = -i;
	motor[UR] = k;
	motor[UL] = -k;
	motor[URT] = k;
	motor[ULT] = -k;
	wait1Msec(t);
}

void Servosetup() // initialization
{
	motor[FR] = 0;
	motor[BR] = 0;
	motor[FL] = 0;
	motor[BL] = 0;
	motor[UR] = 0;
  motor[UL] = 0;
  motor[URT] = 0;
  motor[ULT] = 0;
	servo[servoBall] = 127;
	servo[servoTube] = 70;
	servo[servoMvClaws] = 70;
	servo[servoMvClaws2] = 140;
	servo[servoMvClaws3] = 261 - ServoValue[servoMvClaws];
	nMotorEncoder[FR] = 0;
	nMotorEncoder[FL] = 0;
	nMotorEncoder[BR] = 0;
	nMotorEncoder[BL] = 0;
	nMotorEncoder[UR] = 0;
	motor[motorB]= 0;
	motor[motorC] = 0;
	nMotorEncoder[UL] = 0;
	nMotorEncoder[URT] = 0;
	nMotorEncoder[ULT] = 0;
}


void zero()
{
  L_R_UP(0, 0, 0, 1);
}

void motion_elevator(int l, int h)
{
	nMotorEncoder[BL] = 0;
	nMotorEncoder[UL] = 0;
	while (-nMotorEncoder[BL] < l && -nMotorEncoder[UL] < h)
	{
  		L_R_UP(20, 20, 100, 1);
  }
  zero();
  while (-nMotorEncoder[BL] < l)
	{
			L_R(20, 20, 1);
	}
	zero();
}

void motion(int l_ramp_goal, int a) // moving to rolling goal and capture it
{
	int enc;
	int pow = 100;
  nMotorEncoder[FR] = 0;
	nMotorEncoder[BL] = 0;
  /*L_R(a * -100, a * -100, 1500);
  enc = nMotorEncoder[BL];
  nxtDisplayBigTextLine(1, "%i", enc);
  if(a * nMotorEncoder[BL] < 10)
  {
  	while(true)
  	{
  		for (; pow >= 0; pow--)
  		{
        L_R(-pow, -pow, 5);
        enc = nMotorEncoder[BL];
        nxtDisplayBigTextLine(2, "%i", enc);
      }
  	}
  }
 /* if (SensorValue[S3] == color)
  {
  	  nMotorEncoder[BR] = 0;
    	nMotorEncoder[BL] = 0;*/
	/*while(a * nMotorEncoder[BL] < l_ramp_goal - 4000)// * 1024 /(3.1415 * 10 ))// - 50)
	{
    L_R(a * -100, a * -100, 1);
    enc = nMotorEncoder[BL];
    nxtDisplayBigTextLine(2, "%i", enc);
  }
  for (int pow = a * 100; pow >= a * 20; pow--)
  {
  	L_R(-pow, -pow, 1);
  }*/
  while(a * nMotorEncoder[BL] < l_ramp_goal)
	{
    L_R(a * -20, a * -20, 1);
  }
  servo[servoMvClaws] = 17;
  servo[servoMvClaws3] = 261 - ServoValue[servoMvClaws];
  while(a * nMotorEncoder[BL] < l_ramp_goal + 200)
  {
    L_R(a * -20, a * -20, 1);
  }

  zero();
}

void elevator(int h) // raise the bucket and overturn it
{
	int enc;
	nMotorEncoder[UL] = 0;
  UP(100, 1000);
  if(-nMotorEncoder[UL] < 10)
  {
    while(true)
    {
  	  UP(0, 1);
    }
  }

 	while(-nMotorEncoder[UL] < h)
	{
    UP(100, 1);
  }

  UP(0, 1);

  servo[servoTube] = 245;
  wait1Msec(3500);

  servo[servoTube] = 70;

  while(nMotorEncoder[UL] < -10)
  {
    UP(-100, 1);
  }

  UP(0, 1);
}

void R(float l_ramp_goal, int pow) // turn by right wheel pair
{
	nMotorEncoder[FR] = 0;
	int sign = abs(pow) / pow;
	while(sign * nMotorEncoder[FR] /*/ 1000) * 3.14159265 * 10*/ < l_ramp_goal)
	{
    L_R(0, pow, 1);
  }

  motor[FR] = pow;
  motor[BR] = pow;

  zero();
}

void L(float l_ramp_goal, int pow) // turn by left wheel pair
{
	nMotorEncoder[BL] = 0;
	int sign = abs(pow) / -pow;
	while(sign * nMotorEncoder[BL] /*/ 1000) * 3.14159265 * 10*/ < l_ramp_goal)
	{
    L_R(pow, 0, 1);
    nxtDisplayBigTextLine(2, "%i", nMotorEncoder[FR]);
  }

  motor[FL] = pow;
  motor[BL] = pow;

  zero();
}

void rotate(float l_ramp_goal) // moving on circle
{
	wait1Msec(500);
	nMotorEncoder[BL] = 0;
	nMotorEncoder[FR] = 0;
	while(nMotorEncoder[FR] /*/ 1000) * 3.14159265 * 10*/ < l_ramp_goal)
	{
    L_R(-60, 100, 1);
  }

  L_R(100, 100, 1);

  zero();
}

void rotate2(float l_ramp_goal) // "tank turning"
{
	wait1Msec(500);
	nMotorEncoder[BL] = 0;
	nMotorEncoder[FR] = 0;
	while(-nMotorEncoder[FR] /*/ 1000) * 3.14159265 * 10*/ < l_ramp_goal)
	{
    L_R(50, -100, 1);
  }
  L_R(100, 100, 1);

  zero();
}

void LR(int pow, float l_ramp_goal) // moving
{
	nMotorEncoder[BL] = 0;
	int sign = abs(pow) / -pow;
	while(sign * nMotorEncoder[BL] /*/ 1000) * 3.14159265 * 10*/ < l_ramp_goal)
	{
	  motor[FR] = -pow;
	  motor[BR] = -pow;
	  motor[FL] = -pow;
	  motor[BL] = -pow;
  }

  motor[FR] = 0;
  motor[BR] = 0;
  motor[FL] = 0;
  motor[BL] = 0;
}

task main()
{
	 Servosetup();
	 waitForStart()
   servo[servoMvClaws] = 55;
   servo[servoMvClaws3] = 261 - ServoValue[servoMvClaws];
   motion(9500, 1); // ride to the 60cm goal
   //elevator(7300); // put the ball to 60cm goal
   rotate(3000);// { rotate with
   L(1500, -100);// 60cm goal }
   LR(-20, 1500); // go back with 60cm goal
   servo[servoMvClaws] = 55; // { release
   servo[servoMvClaws3] = 261 - ServoValue[servoMvClaws]; // 60cm goal}
   LR(20, 1500); // return
   rotate2(3000); // rotate to 90cm goal and stop near the 60cm goal
   servo[servoMvClaws2] = 0; // capture to 30cm goal
   rotate2(1000); // rotate to 90cm goal
   motion(1500, 1); // ride to the 90cm goal and capture it
   //elevator(10000); // put the ball to 90cm goal
   R(1500, 100); // rotate to the parking zone
   LR(50, 10000); // move rolling goals to the parking zone
   L(2000, 100); // rotate in the parking zone
   LR(50, 1000); // moving in parking zone*/
	while(true)
	{
		zero();
  }
}
